name: test-demo-proj
on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: ls -la
      - run: pwd

  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: Step one of job 2
        uses: actions/checkout@v4
      - name: Step two of job 2
        run: pwd

  dependent-job-1:
    needs: [job1, job2]
    runs-on: macos-latest
    name: A job that run on Diff
    steps:
      - run: pwd
      - name: new Step
        run: ls
      - run: env

  job3:
    name: test job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: run test
      run: mvn test

