name: test-demo-proj
on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: ls -la
      - run: pwd

  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: Step one of job 2
        uses: actions/checkout@v4
      - name: Step two /2
        run: pwd

  dependent-job-1:
    needs: [job1, job2]
    runs-on: macos-latest
    name: A job that run on Diff
    steps:
      - run: pwd
      - name: new Step
        run: ls
      - run: env

  job3:
    name: third job
    runs-on: windows-latest
    steps:
      - name: Step one of job 4
        uses: actions/checkout@v4
      - name: Step two /2
        run: pwd
